# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: w4po.ExplorerTabUtility
PackageVersion: 3.0.0
PackageLocale: en-US
Publisher: w4po
PublisherUrl: https://github.com/w4po
PublisherSupportUrl: https://github.com/w4po/ExplorerTabUtility/issues
PackageName: ExplorerTabUtility
PackageUrl: https://github.com/w4po/ExplorerTabUtility
License: MIT
ShortDescription: 'Explorer Tab Utility: Force new windows to tabs. Streamline navigation!'
ReleaseNotesUrl: https://github.com/w4po/ExplorerTabUtility/releases/tag/v3.0.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/w4po/ExplorerTabUtility/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
